export const LOADING = "LOADING";
export const REQUEST_FAILED = "REQUEST_FAILED";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_ALL_COMPANIES = "GET_ALL_COMPANIES";
export const GET_COMPANY = "GET_COMPANY";
export const GET_MY_COMPANY = "GET_MY_COMPANY";
export const CREATE_COMPANY = "CREATE_COMPANY";
export const ADD_USER_TO_COMPANY = "ADD_USER_TO_COMPANY";
export const SEND_CONNECTION_REQUEST = "SEND_CONNECTION_REQUEST";
export const ACCEPT_CONNECTION_REQUEST = "ACCEPT_CONNECTION_REQUEST";
export const REJECT_CONNECTION_REQUEST = "REJECT_CONNECTION_REQUEST";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USER = "GET_USER";
export const GET_PROFILE = "GET_PROFILE";
export const SEARCH_USERS = "SEARCH_USERS";
export const CANCEL_SEARCH = "CANCEL_SEARCH";
