//AUTH ACTIONS
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const AUTHENTICATING = "AUTHENTICATING";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

//COMPANIES ACTIONS
export const LOADING_COMPANIES = "LOADING_COMPANIES";
export const COMPANIES_REQUEST_FAILED = "COMPANIES_REQUEST_FAILED";
export const GET_ALL_COMPANIES = "GET_ALL_COMPANIES";
export const GET_COMPANY = "GET_COMPANY";
export const GET_MY_COMPANY = "GET_MY_COMPANY";
export const CREATE_COMPANY = "CREATE_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const ADD_USER_TO_COMPANY = "ADD_USER_TO_COMPANY";
export const GET_CONNECTIONS_REQUEST = "GET_CONNECTIONS_REQUEST";
export const SEND_CONNECTION_REQUEST = "SEND_CONNECTION_REQUEST";
export const ACCEPT_CONNECTION_REQUEST = "ACCEPT_CONNECTION_REQUEST";
export const REJECT_CONNECTION_REQUEST = "REJECT_CONNECTION_REQUEST";

//USERS ACTIONS
export const LOADING_USERS = "LOADING_USERS";
export const USERS_REQUEST_FAILED = "USERS_REQUEST_FAILED";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USER = "GET_USER";
export const GET_PROFILE = "GET_PROFILE";
export const ADD_COMPANY_TO_USER = "ADD_COMPANY_TO_USER";
export const SEARCH_USERS = "SEARCH_USERS";
export const CANCEL_SEARCH = "CANCEL_SEARCH";
